services:
  - type: web
    name: messenger
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: RESEND_API_KEY
        value: re_GmjjZNDq_JRcmAmEnro4crgUKbyGBJNZc
    healthCheckPath: /api/health
